system:
  cpus: 1
  gpus: 1
  seed: 1
  
dataset:
  training:
    s3vol01700:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_01700/img.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_01700/label_v3.h5"
    s3vol02299:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_02299/img.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_02299/label_v3.h5"
    s3vol02400:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_02400/img_zyx_2400-2656_5700-5956_2770-3026.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_02400/label_v1_diane.h5"
    # s3vol02684:
    # images: ["~/dropbox/40_gt/13_wasp_sample3/vol_02284/img_zyx_2400-2656_5700-5956_2770-3026.h5",]
    #  label: "~/dropbox/40_gt/13_wasp_sample3/vol_0684/label_v1_diane.h5"
    s3vol02794:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_02794/img_zyx_2794-3050_5811-6067_8757-9013.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_02794/seg_v1_cropped.h5"
    s3vol03290:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_03290/img_zyx_3290-3546_2375-2631_8450-8706.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_03290/label_v1.h5"
    s3vol03700:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_03700/img_zyx_3700-3956_5000-5256_4250-4506.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_03700/label_v3.h5"
    s3vol03998:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_03998/img.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_03998/label_v1.h5"
    s3vol04900:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_04900/img.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_04900/label_v1.h5"
    s3vol05250:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_05250/img_zyx_5250-5506_4600-4856_5500-5756.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_05250/label_v3_remove_contact.h5"
    s3vol05450:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_05450/img_zyx_5450-5706_5350-5606_7000-7256.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_05450/label_v4_chiyip.h5"
  validation:
    s3vol04000:
      images: ["~/dropbox/40_gt/13_wasp_sample3/vol_04000/img_zyx_4000-4256_3400-3656_8150-8406.h5",]
      label: "~/dropbox/40_gt/13_wasp_sample3/vol_04000/label_v3.h5"
model:
  in_channels: 1
  out_channels: 3

train:
  iter_start: 0
  iter_stop: 1000000
  class_rebalance: false
  # batch size per GPU
  # The dataprovider should provide nGPU*batch_size batches!
  batch_size: 1
  output_dir: "./"
  patch_size: [128, 128, 128]
  learning_rate: 0.001
    #training_interval: 200
    #validation_interval: 2000
  training_interval: 2
  validation_interval: 4